name: Release

on:
  workflow_dispatch:
    inputs:
      force:
        description: Whether forcing to publish a release
        required: true
        type: boolean
      release_version:
        description: Version to publish (vX.Y.Z)
        required: true
        type: string
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Setup | GitHub App Token
        uses: actions/create-github-app-token@v1.11.6
        id: bot
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
      - uses: googleapis/release-please-action@v4.2.0
        id: release_please
        with:
          token: ${{ steps.bot.outputs.token }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
    outputs:
      release_created: ${{ steps.release_please.outputs.release_created }}
      tag_name: ${{ steps.release_please.outputs.tag_name }}
  publish:
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created || github.event.inputs.force }}
    env:
      VERSION: ${{ needs.release-please.outputs.tag_name || inputs.release_version }}
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
      - name: Setup | Deno
        uses: denoland/setup-deno@v1.5.2
        with:
          deno-version: v1.x
      - name: Publish | publish to jsr.io
        run: deno publish
